AllCops:
  Exclude:
    - db/migrate/*
    - lib/pay/version.rb
    - test/dummy/**/*
    - test/test_helper.rb

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

ClassVars:
  Enabled: false

SpecialGlobalVars:
  Enabled: false
