language: ruby
cache: bundler
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
before_install:
  - yes | gem update --system --force
  - gem install bundler
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake test
