name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev
          gem update --system
          gem install bundler
          bundle install --path vendor/bundle --jobs 4 --retry 3

      - name: StandardRb check
        run: bundle exec standardrb

      - name: Run tests
        env:
          RAILS_ENV: test
          STRIPE_PRIVATE_KEY: ${{ secrets.STRIPE_PRIVATE_KEY }}
          DATABASE_URL: postgres://postgres:password@localhost:5432/test
        run: |
          bin/rails db:test:prepare
          bin/rails test
